// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconMinus: typeof import('~icons/mi/nus')['default']
    IconMinusCircle: typeof import('~icons/mi/nus-circle')['default']
    IconRight: typeof import('~icons/ri/ght')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
